version: '3.0'
services:
  backend:
    container_name: main-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python app.py'
    ports:
      - 8001:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"       
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    container_name: main-queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    extra_hosts:
      - "host.docker.internal:host-gateway"     
    depends_on:
      - db

  db:
    container_name: main-db
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgresql/data/
    ports:
      - 5436:5432
